# -*- coding: utf-8 -*-
"""praktikum 2 jb2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtELnnp0N1_oYwy3ZYC9Bt-5Fbc4m5tC
"""

# Modul geometri.py berisi fungsi terkait geometri

def hitung_luas_persegi(sisi):
    return sisi * sisi

def hitung_luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

def hitung_luas_lingkaran(jari_jari):
    return 3.14 * (jari_jari ** 2)

def hello_pray():
    return "Echo hallo pray"

# File utama main.py yang mengimpor modul geometri.py

# Create geometri.py file dynamically from the content of the 'geometri' cell.
geometri_content = """
# Modul geometri.py berisi fungsi terkait geometri

def hitung_luas_persegi(sisi):
    return sisi * sisi

def hitung_luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

def hitung_luas_lingkaran(jari_jari):
    return 3.14 * (jari_jari ** 2)

def hello_pray():
    return "Echo hallo pray"
"""

with open("geometri.py", "w") as f:
    f.write(geometri_content)

# Mengimpor modul geometri
import geometri

def main():
    # Menggunakan fungsi dari modul meong (geometri)
    luas_persegi = geometri.hitung_luas_persegi(5)
    print(f"Luas persegi dengan sisi 5 adalah: {luas_persegi}")

    luas_persegi_panjang = geometri.hitung_luas_persegi_panjang(10, 5)
    print(f"Luas persegi panjang dengan panjang 10 dan lebar 5 adalah: {luas_persegi_panjang}")

    luas_lingkaran = geometri.hitung_luas_lingkaran(7)
    print(f"Luas lingkaran dengan jari-jari 7 adalah: {luas_lingkaran}")

if __name__ == "__main__":
    main()